LocalBaseUrl:  http://localhost:1317
LocalAccount1Address: cosmos1ht7y9zx4n4wnvwmgyqm8309xj2yulwklj54h5j
LocalAccount2Address: cosmos1235em592dc22gehs9z44reqtuy2hqulndd54zt
LocalAccount1PrivateKey: |-
  -----BEGIN TENDERMINT PRIVATE KEY-----
  kdf: bcrypt
  salt: C586A3498B0298905ABE7D6DBADBCB87

  FascN+0QNtdvs/Wh3PzxwHBNmPr5nh+yZA3g4aJD6CHbOPLCYnD7ozt4sZW3LvQu
  Zs2mQ5J0t9siMmKCi/1RZ0CoweBz0pUKvO8Kqek=
  =K7Bt
  -----END TENDERMINT PRIVATE KEY-----
Validator1Passphrase: 11111111
LocalAccount1Passphrase: 11111111
LocalAccount2PrivateKey: |-
  -----BEGIN TENDERMINT PRIVATE KEY-----
  kdf: bcrypt
  salt: 00793DC1E5C67A8815C1660BF0FEC268

  4dZKIO+JkOXOKwtgkrHThz6DsFqYVOUTAJGpxjU2NAvmjImUepzOQO3HbS3VPpcW
  neZJeGwgteC8ukJoq4OJBtelDG0r0BBtFWRGo80=
  =xY68
  -----END TENDERMINT PRIVATE KEY-----
LocalAccount2Passphrase: 11111111
LocalDelegator1Address: cosmos18cqk9yh9alcf54fvprqwaa96d4mu65c0aw4suv
LocalDelegator1PrivateKey: |-
  -----BEGIN TENDERMINT PRIVATE KEY-----
  kdf: bcrypt
  salt: 19BF16DE8AC987CD62D899FC7B17DAD4

  qQGZtb3NhlpMoxIKay38HlkVm3rCgT+80i1+vCcTusMJ9r3Qk0DZsea8FYfXZVEM
  jskN0a6SyDdSkFpfEYWHTKiPu3E1mFqNzemG3nk=
  =mqMr
  -----END TENDERMINT PRIVATE KEY-----
LocalDelegator1Passphrase: 11111111
LocalValidator1Address: cosmosvaloper1ht7y9zx4n4wnvwmgyqm8309xj2yulwklhqpzcp
LocalValidator2Address: cosmosvaloper1235em592dc22gehs9z44reqtuy2hqulngeqqwc
CutLongOutput: false
LocalNameserviceBaseUrl: http://localhost:1327
LocalNameserviceOwner1: cosmos184xz9l8g5xrdz0klmnx0vapdmreenvhrgafspq
LocalNameserviceOwner1PrivateKey: |-
  -----BEGIN TENDERMINT PRIVATE KEY-----
  kdf: bcrypt
  salt: FA9B9991F8FF4DEA9153CEEB074C97D7
  type: secp256k1

  +K3HsI6HfdS7mGgdrn73jSKIGBgAwXx6gO/PvaJu+I9Wu6Ulwk/2zRYb4bsDRfIH
  P59u/AdXatvFgl3PHi5liqGtEjCvTO3K+bFz7hw=
  =EK4p
  -----END TENDERMINT PRIVATE KEY-----
LocalNameserviceOwner1Passphrase: 11111111
  